server:
  port: 9091
  servlet:
    context-path: '/hubspot/'

spring:
  profiles:
    active: default
  application:
    name: integration-api
  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: 15708b6f-9682-4a5d-95a9-e937a7e8b30b
            client-secret: 86401324-2cf0-411a-b305-e1ed0bf35751
            authorization-grant-type: authorization_code
            redirect-uri: https://hubspot-api-production.up.railway.app/hubspot/oauth/callback
            scope: crm.objects.contacts.write, crm.objects.contacts.read
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token


hubspot:
  credentials:
    client:
      id: 15708b6f-9682-4a5d-95a9-e937a7e8b30b
      secret: 86401324-2cf0-411a-b305-e1ed0bf35751
    scope: "crm.objects.contacts.write crm.objects.contacts.read"
    redirect:
      uri: https://hubspot-api-production.up.railway.app/hubspot/oauth/callback
  url:
    token: https://api.hubapi.com/oauth/v1/token
    profile: https://api.hubapi.com/oauth/v1/access-tokens/
    contacts: https://api.hubapi.com/crm/v3/objects/contacts
    redirect:
      home:
        url: https://app.hubspot.com/user-guide/
        suffix: ?via=home