spring:
  application:
    name: integration-api
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          hubspot:
            client-id: cce10b2f-146d-4bcf-b68a-5ce7472da2ce
            client-secret: 836ad464-1f3a-4952-a4b0-6257e30fead4
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9091/auth/callback
            scope: crm.objects.contacts.write, crm.objects.contacts.read
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token
server:
  port: 9091

credentials:
  client-id: cce10b2f-146d-4bcf-b68a-5ce7472da2ce
  client-secret: 836ad464-1f3a-4952-a4b0-6257e30fead4
  scope: "crm.objects.contacts.write crm.objects.contacts.read"
  redirect-uri: http://localhost:9091/auth/callback

hubspot:
  url-token: https://api.hubapi.com/oauth/v1/token